Bashly way to validate input
Bashly provides a clean way to add validation functions for our
arguments. It works like this:

- In `bashly.yml`, in the flag configuration we add a line like this:
`validate: function_name`.
- We create a function called `validate_function_name`, and now our
program run it before allowing the user input to pass.
- If the function prints any string to stdout, it is considered an
error. The string will be displayed on screen, as the error message.

In this commit we are using the `validate_positive_integer` for this
purpose.

Another benefit of validating input this way is that Bashly provides a
slightly better error message, with information about the validation
error. Example:

```
$ ./rndm --max foo
validation error in --max MAX:
The argument must be a positive integer. Given value: foo
```

diff --git a/rndm b/rndm
--- a/rndm
+++ b/rndm
@@ -14,8 +14,6 @@ root_command() {
   # src/root_command.sh
   max_number="${args[--max]}"
 
-  validate_positive_integer "$max_number"
-
   if [[ "${args[--web]}" == 1 ]]; then
     curl \
       --silent \
@@ -139,7 +137,6 @@ validate_positive_integer() {
 
   if ! is_positive_integer "$number"; then
     echo "The argument must be a positive integer. Given value: $number"
-    exit 1
   fi
 }
 
@@ -234,6 +231,16 @@ parse_requirements() {
 
   # :command.default_assignments
   [[ -n ${args['--max']:-} ]] || args['--max']="32767"
+
+  # :command.validations
+  # :flag.validations
+  if [[ -v args['--max'] ]]; then
+    validation_output="$(validate_positive_integer "${args['--max']:-}" 2>&1)"
+    if [[ -n "${validation_output}" ]]; then
+      printf "validation error in %s:\n%s\n" "--max MAX" "$validation_output" >&2
+      exit 1
+    fi
+  fi
 
 }
 
