List 'curl' as a dependency
As our script is now using 'curl', it's a dependency, and we should make
it explicit.

When rndm users run the script in an environment where `curl` is not
available, we should give them a clear error message.

By adding a list of dependencies in our `bashly.yml`, Bashly
automatically creates a dependency checking logic for the final script.

Running rndm in an environment without `curl` would fail with a message
like this:

```
$  ./rndm
missing dependency: curl
```

diff --git a/rndm b/rndm
--- a/rndm
+++ b/rndm
@@ -148,6 +148,20 @@ parse_requirements() {
     esac
   done
 
+  # :command.dependencies_filter
+  missing_deps=
+  # :dependency.filter
+  if ! command -v curl >/dev/null 2>&1; then
+    printf "missing dependency: curl\n" >&2
+    missing_deps=1
+  else
+    deps['curl']="$(command -v curl | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
+    exit 1
+  fi
+
   # :command.command_filter
   action="root"
 
